packages:
  - packages/*
  - examples/*
  - tools/*
  - tests
  - docs

catalog:
  "@asyncapi/parser": 3.6.0
  "@changesets/cli": 2.29.8
  "@commitlint/cli": 20.4.1
  "@commitlint/config-conventional": 20.4.1
  "@nestjs/common": 11.1.13
  "@nestjs/config": 4.0.3
  "@nestjs/core": 11.1.13
  "@nestjs/testing": 11.1.13
  "@opentelemetry/api": 1.9.0
  "@orpc/arktype": 1.13.4
  "@orpc/openapi": 1.13.4
  "@orpc/valibot": 1.13.4
  "@orpc/zod": 1.13.4
  "@standard-schema/spec": 1.1.0
  "@swan-io/boxed": 3.2.1
  "@types/amqplib": 0.10.8
  "@types/node": 25.2.1
  "@vitest/coverage-v8": 4.0.18
  amqp-connection-manager: 5.0.0
  amqplib: 0.10.9
  arktype: 2.1.29
  knip: 5.83.0
  lefthook: 2.1.0
  mermaid: 11.12.2
  oxfmt: 0.28.0
  oxlint: 1.43.0
  pino: 10.3.0
  pino-pretty: 13.1.3
  reflect-metadata: 0.2.2
  rxjs: 7.8.2
  sort-package-json: 3.6.1
  testcontainers: 11.11.0
  ts-pattern: 5.9.0
  tsdown: 0.20.3
  tsx: 4.21.0
  turbo: 2.8.3
  typedoc: 0.28.16
  typedoc-plugin-markdown: 4.9.0
  typescript: 5.9.3
  valibot: 1.2.0
  vitepress: 1.6.4
  vitepress-plugin-mermaid: 2.0.17
  vitest: 4.0.18
  yaml: 2.8.2
  zod: 4.3.6
