packages:
  - packages/*
  - samples/*
  - tools/*
  - website

catalog:
  "@changesets/cli": 2.29.8
  "@commitlint/cli": 20.2.0
  "@commitlint/config-conventional": 20.2.0
  "@nestjs/common": 11.0.10
  "@standard-schema/spec": 1.1.0
  "@types/amqplib": 0.10.8
  "@types/node": 25.0.3
  "@vitest/coverage-v8": 4.0.16
  amqplib: 0.10.9
  arktype: 2.1.29
  knip: 5.75.2
  lefthook: 2.0.12
  oxfmt: 0.19.0
  oxlint: 1.34.0
  pino: 10.1.0
  pino-pretty: 13.1.3
  reflect-metadata: 0.2.2
  rxjs: 7.8.1
  sort-package-json: 3.6.0
  testcontainers: 11.10.0
  tsdown: 0.18.1
  tsx: 4.21.0
  turbo: 2.6.3
  typescript: 5.9.3
  valibot: 1.2.0
  vitepress: 1.6.4
  vitest: 4.0.16
  zod: 4.2.1

strictPeerDependencies: false
