packages:
  - packages/*
  - examples/*
  - tools/*
  - tests
  - docs

catalog:
  "@asyncapi/parser": 3.4.0
  "@changesets/cli": 2.29.8
  "@commitlint/cli": 20.3.1
  "@commitlint/config-conventional": 20.3.1
  "@nestjs/common": 11.1.11
  "@nestjs/config": 4.0.2
  "@nestjs/core": 11.1.11
  "@nestjs/testing": 11.1.11
  "@opentelemetry/api": 1.9.0
  "@orpc/arktype": 1.13.4
  "@orpc/openapi": 1.13.4
  "@orpc/valibot": 1.13.4
  "@orpc/zod": 1.13.4
  "@standard-schema/spec": 1.1.0
  "@swan-io/boxed": 3.2.1
  "@types/amqplib": 0.10.8
  "@types/node": 25.0.6
  "@vitest/coverage-v8": 4.0.17
  amqp-connection-manager: 5.0.0
  amqplib: 0.10.9
  arktype: 2.1.29
  knip: 5.80.2
  lefthook: 2.0.14
  mermaid: 11.12.2
  oxfmt: 0.24.0
  oxlint: 1.39.0
  pino: 10.1.1
  pino-pretty: 13.1.3
  reflect-metadata: 0.2.2
  rxjs: 7.8.2
  sort-package-json: 3.6.0
  testcontainers: 11.11.0
  ts-pattern: 5.9.0
  tsdown: 0.19.0
  tsx: 4.21.0
  turbo: 2.7.4
  typedoc: 0.28.16
  typedoc-plugin-markdown: 4.9.0
  typescript: 5.9.3
  valibot: 1.2.0
  vitepress: 1.6.4
  vitepress-plugin-mermaid: 2.0.17
  vitest: 4.0.17
  yaml: 2.8.2
  zod: 4.3.5

strictPeerDependencies: false
