export {
  defineQueueBinding,
  defineExchangeBinding,
  defineConsumer,
  defineContract,
  defineExchange,
  defineMessage,
  definePublisher,
  defineQueue,
  definePublisherFirst,
  defineConsumerFirst,
  defineQueueWithRetry,
} from "./builder.js";
export type {
  PublisherFirstResult,
  PublisherFirstResultWithRoutingKey,
  ConsumerFirstResult,
  ConsumerFirstResultWithRoutingKey,
  RoutingKey,
  BindingPattern,
  MatchingRoutingKey,
  QueueWithRetryResult,
  DefineQueueWithRetryOptions,
  QueueTtlBackoffRetryOptions,
} from "./builder.js";
export type {
  AnySchema,
  BindingDefinition,
  QueueBindingDefinition,
  ExchangeBindingDefinition,
  ClassicQueueOptions,
  CompressionAlgorithm,
  ConsumerDefinition,
  ContractDefinition,
  DeadLetterConfig,
  DefineQueueOptions,
  ExchangeDefinition,
  FanoutExchangeDefinition,
  DirectExchangeDefinition,
  TopicExchangeDefinition,
  BaseExchangeDefinition,
  MessageDefinition,
  PublisherDefinition,
  QueueDefinition,
  QueueType,
  QuorumQueueOptions,
  InferPublisherNames,
  InferConsumerNames,
  // Retry configuration types
  TtlBackoffRetryConfig,
  QuorumNativeRetryConfig,
  QueueRetryConfig,
} from "./types.js";

// Validation utilities
export {
  ContractValidationError,
  ValidationErrorCode,
  QueueConstraints,
  // Zod schemas
  MaxPrioritySchema,
  DeliveryLimitSchema,
  QueueNameSchema,
  ExchangeNameSchema,
  ExchangeTypeSchema,
  RoutingKeySchema,
  // Validation functions
  validateMaxPriority,
  validateDeliveryLimit,
  validateQueueName,
  validateExchangeName,
  validateExchangeType,
  validateRoutingKey,
  validateContract,
  assertValidContract,
  hasConsumer,
  getConsumerNames,
  assertConsumerExists,
  assertHandlersMatchConsumers,
} from "./validation.js";
export type { ContractValidationResult, ExchangeType } from "./validation.js";
